<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <link rel="apple-touch-icon" sizes="76x76" href="../assets/dashboard/img/apple-icon.png" />
    <link rel="icon" type="image/png" href="../assets/dashboard/img/favicon.png" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <title>UFF Dashboard</title>
    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
    <meta name="viewport" content="width=device-width" />
    <link href="../assets/dashboard/css/bootstrap.min.css" rel="stylesheet" />
    <link href="../assets/dashboard/css/material-dashboard.css?v=1.2.1" rel="stylesheet" />
    <link href="../assets/dashboard/css/demo.css" rel="stylesheet" />
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Material+Icons" />
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>

<body>
    <div class="wrapper">
        <div class="sidebar" data-active-color="rose" data-background-color="black" data-image="../assets/dashboard/img/sidebar-1.jpg">
            <div class="logo">
                <a href="/" class="simple-text logo-mini">
                    UFF
                </a>
                <a href="/" class="simple-text logo-normal">
                    Dashboard
                </a>
            </div>
            <div class="sidebar-wrapper">
                <div class="user">
                    <div class="photo">
                        <img src="<?php echo($uff->image); ?>" width="34" height="34"/>
                    </div>
                    <div class="info">
                        <a data-toggle="collapse" href="#collapseExample" class="collapsed">
                            <span>
                                <?php echo($uff->nome); ?>
                                <b class="caret"></b>
                            </span>
                        </a>
                        <div class="clearfix"></div>
                        <div class="collapse" id="collapseExample">
                            <ul class="nav">
                                <li>
                                    <a href="#">
                                        <span class="sidebar-mini"> MP </span>
                                        <span class="sidebar-normal"> Meu Perfil </span>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <span class="sidebar-mini"> C </span>
                                        <span class="sidebar-normal"> Configurações </span>
                                    </a>
                                </li>
                                <li>
                                    <a href="/logout">
                                        <span class="sidebar-mini"> S </span>
                                        <span class="sidebar-normal"> Sair </span>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
                <ul class="nav">
    <li>
        <a href="/">
            <i class="material-icons">dashboard</i>
            <p> Dashboard </p>
        </a>
    </li>
    <li>
        <a href="/plano-de-estudo">
            <i class="material-icons">school</i>
            <p> Plano de Estudo </p>
        </a>
    </li>
    <li>
            <a href="/historico">
                <i class="material-icons">history</i>
                <p> Histórico </p>
            </a>
        </li>
</ul>
            </div>
        </div>
        <div class="main-panel">
            <nav class="navbar navbar-transparent navbar-absolute">
                <div class="container-fluid">
                    <div class="navbar-minimize">
                        <button id="minimizeSidebar" class="btn btn-round btn-white btn-fill btn-just-icon">
                            <i class="material-icons visible-on-sidebar-regular">more_vert</i>
                            <i class="material-icons visible-on-sidebar-mini">view_list</i>
                        </button>
                    </div>
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="#"></a>
                    </div>
                    <div class="collapse navbar-collapse">
                        <ul class="nav navbar-nav navbar-right">
                            <li>
                                <a href="#pablo" class="dropdown-toggle" data-toggle="dropdown">
                                    <i class="material-icons">dashboard</i>
                                    <p class="hidden-lg hidden-md">Dashboard</p>
                                </a>
                            </li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                    <i class="material-icons">notifications</i>
                                    <span class="notification">5</span>
                                    <p class="hidden-lg hidden-md">
                                        Notifications
                                        <b class="caret"></b>
                                    </p>
                                </a>
                                <ul class="dropdown-menu">
                                    <li>
                                        <a href="#">Mike John responded to your email</a>
                                    </li>
                                    <li>
                                        <a href="#">You have 5 new tasks</a>
                                    </li>
                                    <li>
                                        <a href="#">You're now friend with Andrew</a>
                                    </li>
                                    <li>
                                        <a href="#">Another Notification</a>
                                    </li>
                                    <li>
                                        <a href="#">Another One</a>
                                    </li>
                                </ul>
                            </li>
                            <li>
                                <a href="#pablo" class="dropdown-toggle" data-toggle="dropdown">
                                    <i class="material-icons">person</i>
                                    <p class="hidden-lg hidden-md">Profile</p>
                                </a>
                            </li>
                            <li class="separator hidden-lg hidden-md"></li>
                        </ul>
                        <form class="navbar-form navbar-right" role="search">
                            <div class="form-group form-search is-empty">
                                <input type="text" class="form-control" placeholder=" Search ">
                                <span class="material-input"></span>
                            </div>
                            <button type="submit" class="btn btn-white btn-round btn-just-icon">
                                <i class="material-icons">search</i>
                                <div class="ripple-container"></div>
                            </button>
                        </form>
                    </div>
                </div>
            </nav>
            
<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card card-plain">
                    <div class="card-header card-header-icon" data-background-color="gray">
                        <i class="material-icons">school</i>
                    </div>
                    <h4 class="card-title">Plano de Estudo</h4>
                    <p class="category">Este é o seu plano de estudo do período corrente.</p>
                    <br>
                    <div class="card-content" class="ps-child">
                        <div id="fullCalendar"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

            <footer class="footer">
                <div class="container-fluid">
                    <nav class="pull-left">
                        <ul>
                            <li>
                                <a href="/sobre">
                                    Sobre Nós
                                </a>
                            </li>
                        </ul>
                    </nav>
                    <div class="copyright pull-right">
                            &copy;
                            <script>
                                document.write(new Date().getFullYear())
                            </script>, UFF Dashboard
                        </div>
                </div>
            </footer>
        </div>
    </div>
</body>
<script src="../assets/dashboard/js/jquery-3.2.1.min.js" type="text/javascript"></script>
<script src="../assets/dashboard/js/bootstrap.min.js" type="text/javascript"></script>
<script src="../assets/dashboard/js/material.min.js" type="text/javascript"></script>
<script src="../assets/dashboard/js/perfect-scrollbar.jquery.min.js" type="text/javascript"></script>
<script src="../assets/dashboard/js/arrive.min.js" type="text/javascript"></script>
<script src="../assets/dashboard/js/jquery.validate.min.js"></script>
<script src="../assets/dashboard/js/moment.min.js"></script>
<script src="../assets/dashboard/js/chartist.min.js"></script>
<script src="../assets/dashboard/js/jquery.bootstrap-wizard.js"></script>
<script src="../assets/dashboard/js/bootstrap-notify.js"></script>
<script src="../assets/dashboard/js/bootstrap-datetimepicker.js"></script>
<script src="../assets/dashboard/js/jquery-jvectormap.js"></script>
<script src="../assets/dashboard/js/nouislider.min.js"></script>
<script src="../assets/dashboard/js/jquery.select-bootstrap.js"></script>
<script src="../assets/dashboard/js/jquery.datatables.js"></script>
<script src="../assets/dashboard/js/sweetalert2.js"></script>
<script src="../assets/dashboard/js/jasny-bootstrap.min.js"></script>
<script src="../assets/dashboard/js/fullcalendar.min.js"></script>
<script src="../assets/dashboard/js/jquery.tagsinput.js"></script>
<script src="../assets/dashboard/js/material-dashboard.js?v=1.2.1"></script>

<script type="text/javascript">
    $(document).ready(function() {
        initFullCalendar();
    });

    initFullCalendar = function() {
        $calendar = $('#fullCalendar');

        today = new Date();
        y = today.getFullYear();
        m = today.getMonth();
        d = today.getDate();

        $calendar.fullCalendar({
            viewRender: function(view, element) {
                // We make sure that we activate the perfect scrollbar when the view isn't on Month
                if (view.name != 'month') {
                    $(element).find('.fc-scroller').perfectScrollbar();
                }
            },
            header: {
                left: 'title',
                center: 'month,basicWeek,basicDay',
                right: 'prev,next today'
            },
            defaultView: 'basicDay',
            defaultDate: today,
            views: {
                month: { // name of view
                    titleFormat: 'MMMM YYYY'
                    // other view-specific options here
                },
                week: {
                    titleFormat: " MMMM D YYYY"
                },
                day: {
                    titleFormat: 'D MMM, YYYY'
                }
            },

            // color classes: [ event-blue | event-azure | event-green | event-orange | event-red ]
            events: [
                {
                    title: 'Lunch',
                    start: new Date(y, m, d, 6, 0),
                    end: new Date(y, m, d, 8, 0),
                    allDay: false,
                    className: 'event-red'
                }
            ]
        });
    }
</script>


</html>